platform: linux/arm

clone:
  git:
    image: armswarmdrone/git

pipeline:
  build_and_publish:
    image: armswarmdrone/docker
    repo: quay.io/armswarm/traefik
    build_args:
      - TRAEFIK_VERSION=1.2.3
    tag: [ "v1.2.3-alpine", "1.2.3-alpine", "v1.2-alpine", "1.2-alpine", "morbier-alpine"]
    when:
      branch: master
      event: push

  notify:
    image: armswarmdrone/slack
    when:
      status: [ failure, success ]
